
### Data preprocessing
- pip install pandas

In [5]:
import pandas as pd

In [6]:
df_employee = pd.read_csv('Employees.csv')
df_customer = pd.read_csv('Customers.csv')
df_department = pd.read_csv('Departments.csv')
df_inventory = pd.read_csv('Inventory.csv')
df_order = pd.read_csv('Orders.csv')
df_product = pd.read_csv('Products.csv')
df_store = pd.read_csv('Stores.csv')

In [7]:
## show how many columns
print(len(df_inventory.columns))

20

In [8]:
df_employee.columns

Index(['EmployeeId', 'FIRST_NAME', 'LAST_NAME', 'BIRTHDAY', 'EMAIL',
       'PHONE_NUMBER', 'HIRE_DATE', 'JOB_TITLE', 'AGE', 'SALARY', 'COMMISSION',
       'ManagerId', 'DepartmentId', 'Name'],
      dtype='object')

In [9]:
df_customer.columns

Index(['Customer Number', 'First Name', 'Last Name', 'Address', 'City',
       'Province', 'Country', 'Postal Code', 'Phone', 'email'],
      dtype='object')

In [10]:
df_department.columns

Index(['DepartmentId', 'Department'], dtype='object')

In [11]:
df_inventory.columns

Index(['warehouse Number', 'Product Number', 'On Hand Units',
       'In Transit Units', 'On Order Units', 'Transfer On Order Units',
       'Allocated Units', 'Held Units', 'Reserve On Hand', 'Reserve On Order',
       'Available Units', 'Average Cost', 'On Hand Cost', 'In Transit Cost',
       'Transfer On Order Cost', 'Allocated Cost', 'Held Cost',
       'Reserve On Hand Cost', 'Reserve On Order Cost', 'On Order Cost'],
      dtype='object')

In [12]:
df_order.columns

Index(['Customer Number', 'Store Number', 'order number', 'Order Date',
       'Target Ship Date', 'Product Number', 'Requested Quantity',
       'Ordered Quantity', 'Unit Cost', 'Unit Retail', 'Part number',
       'Shipped Quantity'],
      dtype='object')

In [13]:
df_product.columns

Index(['Product Number', 'Part number', 'SKU - Description', 'Price',
       'Category', 'Category Number'],
      dtype='object')

In [14]:
df_store.columns

Index(['Store Number', 'Salesperson', 'ManagerId', 'Store Name', 'Store City',
       'Store Province', 'Region Number', 'Warehouse Number',
       'District Number', 'Language', 'Location'],
      dtype='object')

In [15]:
print(df_employee.isnull().any())
print("==============")
print(df_employee.isnull().any().any())

EmployeeId      False
FIRST_NAME      False
LAST_NAME       False
BIRTHDAY        False
EMAIL           False
PHONE_NUMBER    False
HIRE_DATE       False
JOB_TITLE       False
AGE             False
SALARY          False
COMMISSION       True
ManagerId        True
DepartmentId    False
Name            False
dtype: bool
==============
True

In [16]:
print(df_customer.isnull().any())
print("==============")
print(df_customer.isnull().any().any())

Customer Number    False
First Name         False
Last Name          False
Address            False
City               False
Province            True
Country             True
Postal Code        False
Phone              False
email              False
dtype: bool
==============
True

In [17]:
print(df_department.isnull().any())
print("==============")
print(df_department.isnull().any().any())

DepartmentId    False
Department      False
dtype: bool
==============
False

In [18]:
print(df_inventory.isnull().any())
print("==============")
print(df_inventory.isnull().any().any())

warehouse Number           False
Product Number             False
On Hand Units              False
In Transit Units           False
On Order Units             False
Transfer On Order Units    False
Allocated Units            False
Held Units                 False
Reserve On Hand             True
Reserve On Order            True
Available Units            False
Average Cost               False
On Hand Cost               False
In Transit Cost            False
Transfer On Order Cost     False
Allocated Cost             False
Held Cost                  False
Reserve On Hand Cost        True
Reserve On Order Cost       True
On Order Cost              False
dtype: bool
==============
True

In [19]:
print(df_order.isnull().any())
print("==============")
print(df_order.isnull().any().any())

Customer Number       False
Store Number          False
order number          False
Order Date            False
Target Ship Date       True
Product Number         True
Requested Quantity     True
Ordered Quantity       True
Unit Cost              True
Unit Retail           False
Part number            True
Shipped Quantity      False
dtype: bool
==============
True

In [20]:
print(df_product.isnull().any())
print("==============")
print(df_product.isnull().any().any())

Product Number       False
Part number           True
SKU - Description    False
Price                False
Category             False
Category Number      False
dtype: bool
==============
True

In [21]:
print(df_store.isnull().any())
print("==============")
print(df_store.isnull().any().any())

Store Number        False
Salesperson         False
ManagerId           False
Store Name          False
Store City          False
Store Province      False
Region Number       False
Warehouse Number    False
District Number     False
Language             True
Location            False
dtype: bool
==============
True

In [22]:
print(df_employee.isnull().values.any())

True

In [23]:
print(df_customer.isnull().values.any())

True

In [24]:
df_employee.isnull().sum()

EmployeeId       0
FIRST_NAME       0
LAST_NAME        0
BIRTHDAY         0
EMAIL            0
PHONE_NUMBER     0
HIRE_DATE        0
JOB_TITLE        0
AGE              0
SALARY           0
COMMISSION      27
ManagerId        1
DepartmentId     0
Name             0
dtype: int64

In [25]:
df_customer.isnull().sum()

Customer Number    0
First Name         0
Last Name          0
Address            0
City               0
Province           1
Country            1
Postal Code        0
Phone              0
email              0
dtype: int64

In [26]:
df_department.isnull().sum()

DepartmentId    0
Department      0
dtype: int64

In [27]:
df_inventory.isnull().sum()

warehouse Number                0
Product Number                  0
On Hand Units                   0
In Transit Units                0
On Order Units                  0
Transfer On Order Units         0
Allocated Units                 0
Held Units                      0
Reserve On Hand            296842
Reserve On Order           296842
Available Units                 0
Average Cost                    0
On Hand Cost                    0
In Transit Cost                 0
Transfer On Order Cost          0
Allocated Cost                  0
Held Cost                       0
Reserve On Hand Cost       296842
Reserve On Order Cost      296842
On Order Cost                   0
dtype: int64

In [28]:
df_order.isnull().sum()

Customer Number          0
Store Number             0
order number             0
Order Date               0
Target Ship Date         1
Product Number           1
Requested Quantity       1
Ordered Quantity         1
Unit Cost                1
Unit Retail              0
Part number           1526
Shipped Quantity         0
dtype: int64

In [29]:
df_product.isnull().sum()

Product Number         0
Part number          103
SKU - Description      0
Price                  0
Category               0
Category Number        0
dtype: int64

In [30]:
df_store.isnull().sum()

Store Number        0
Salesperson         0
ManagerId           0
Store Name          0
Store City          0
Store Province      0
Region Number       0
Warehouse Number    0
District Number     0
Language            3
Location            0
dtype: int64

In [31]:
df_employee.dtypes

EmployeeId        int64
FIRST_NAME       object
LAST_NAME        object
BIRTHDAY         object
EMAIL            object
PHONE_NUMBER     object
HIRE_DATE        object
JOB_TITLE        object
AGE               int64
SALARY            int64
COMMISSION      float64
ManagerId       float64
DepartmentId      int64
Name             object
dtype: object

In [32]:
df_customer.dtypes

Customer Number     int64
First Name         object
Last Name          object
Address            object
City               object
Province           object
Country            object
Postal Code        object
Phone              object
email              object
dtype: object

In [33]:
df_department.dtypes

DepartmentId     int64
Department      object
dtype: object

In [34]:
df_inventory.dtypes

warehouse Number             int64
Product Number               int64
On Hand Units                int64
In Transit Units             int64
On Order Units               int64
Transfer On Order Units      int64
Allocated Units              int64
Held Units                   int64
Reserve On Hand            float64
Reserve On Order           float64
Available Units              int64
Average Cost               float64
On Hand Cost               float64
In Transit Cost            float64
Transfer On Order Cost     float64
Allocated Cost             float64
Held Cost                  float64
Reserve On Hand Cost       float64
Reserve On Order Cost      float64
On Order Cost              float64
dtype: object

In [35]:
df_order.dtypes

Customer Number         int64
Store Number            int64
order number            int64
Order Date              int64
Target Ship Date      float64
Product Number        float64
Requested Quantity    float64
Ordered Quantity      float64
Unit Cost             float64
Unit Retail           float64
Part number            object
Shipped Quantity        int64
dtype: object

In [36]:
df_product.dtypes

Product Number         int64
Part number           object
SKU - Description     object
Price                float64
Category              object
Category Number        int64
dtype: object

In [37]:
df_store.dtypes

Store Number         int64
Salesperson         object
ManagerId            int64
Store Name          object
Store City          object
Store Province      object
Region Number        int64
Warehouse Number     int64
District Number      int64
Language            object
Location            object
dtype: object

In [38]:
df_employee.loc[df_employee.duplicated()]

Empty DataFrame
Columns: [EmployeeId, FIRST_NAME, LAST_NAME, BIRTHDAY, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, AGE, SALARY, COMMISSION, ManagerId, DepartmentId, Name]
Index: []

In [39]:
df_customer.loc[df_customer.duplicated()]

Empty DataFrame
Columns: [Customer Number, First Name, Last Name, Address, City, Province, Country, Postal Code, Phone, email]
Index: []

In [40]:
df_department.loc[df_department.duplicated()]

Empty DataFrame
Columns: [DepartmentId, Department]
Index: []

In [41]:
df_inventory.loc[df_inventory.duplicated()]

,warehouse Number,Product Number,On Hand Units,In Transit Units,On Order Units,Transfer On Order Units,Allocated Units,Held Units,Reserve On Hand,Reserve On Order,Available Units,Average Cost,On Hand Cost,In Transit Cost,Transfer On Order Cost,Allocated Cost,Held Cost,Reserve On Hand Cost,Reserve On Order Cost,On Order Cost
3746,99,1011270,0,0,0,0,0,0,NaN,NaN,0,13.7382,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,0.0
3751,99,1011435,0,0,0,0,0,0,NaN,NaN,0,176.7970,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,0.0
3752,99,1011457,0,0,0,0,0,0,NaN,NaN,0,4.4191,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,0.0
3755,99,1011637,0,0,0,0,0,0,NaN,NaN,0,10019.3300,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,0.0
3928,99,1011995,0,0,0,0,0,0,NaN,NaN,0,107.4552,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496550,99,358517,11,0,0,0,0,0,10.0,0.0,1,0.2700,2.9700,0.0,0.0,0.0,0.0,2.700,0.0,0.0
496551,99,492310,30,0,0,0,0,0,10.0,0.0,20,0.8900,26.7000,0.0,0.0,0.0,0.0,8.900,0.0,0.0
496552,99,482324,18,0,0,0,0,0,10.0,0.0,8,3.8862,69.9516,0.0,0.0,0.0,0.0,38.862,0.0,0.0
496553,99,482362,23,0,0,0,0,0,10.0,0.0,13,1.9964,45.9172,0.0,0.0,0.0,0.0,19.964,0.0,0.0
496554,99,482470,22,0,0,0,0,0,10.0,0.0,12,3.4996,76.9912,0.0,0.0,0.0,0.0,34.996,0.0,0.0

In [42]:
df_order.loc[df_order.duplicated()]

Empty DataFrame
Columns: [Customer Number, Store Number, order number, Order Date, Target Ship Date, Product Number, Requested Quantity, Ordered Quantity, Unit Cost, Unit Retail, Part number, Shipped Quantity]
Index: []

In [43]:
df_product.loc[df_product.duplicated()]

Empty DataFrame
Columns: [Product Number, Part number, SKU - Description, Price, Category, Category Number]
Index: []

In [44]:
df_store.loc[df_store.duplicated()]

Empty DataFrame
Columns: [Store Number, Salesperson, ManagerId, Store Name, Store City, Store Province, Region Number, Warehouse Number, District Number, Language, Location]
Index: []

###  Option 1: pip install mysql-connector-python
#### connecting with MYSQL

- if still getting no module found 'mysql', we might want to 

- Create the virtual environment in your dev dir: $ python(3) -m venv venv

    - Virtual environments: If you’re using Conda or venv, activate it first before installing the 'pip install mysql-connector-python'

- Activate the virtual environment: $ . venv/bin/activate (C:\Users\Jake\Desktop\SQL\sql-projects\sql-connect-with-python\venv\Scripts>)

- Install your dependency(ies): $ pip install mysql-connector-python

- on the top right corner, switch to venv(Python 3.13.7), and rerun all, you might
want to pip install pandas again


### please see README.md for Virtual environments purpose

- Conflicting packages: There’s also a different package called mysql-connector (without -python). That one is outdated and can cause conflicts. Make sure you only have mysql-connector-python installed:

    - pip uninstall mysql-connector
    - pip uninstall mysql-connector-python
    - pip install mysql-connector-python

In [7]:
import mysql.connector

try:
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="2diiouli",
        database="trainingdb"
    )

    print("Successfully connected to MySQL database!")

    # You can now interact with the database using the 'mydb' connection object
    # For example, create a cursor and execute queries:
    # mycursor = mydb.cursor()
    # mycursor.execute("SELECT * FROM your_table")
    # results = mycursor.fetchall()
    # for row in results:
    #     print(row)

except mysql.connector.Error as err:
    if err.errno == mysql.connector.errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
    elif err.errno == mysql.connector.errorcode.ER_BAD_DB_ERROR:
        print("Database does not exist")
    else:
        print(err)

finally:
    if 'mydb' in locals() and mydb.is_connected():
        mydb.close()
        print("MySQL connection closed.")

Successfully connected to MySQL database!
MySQL connection closed.

### Option 2
- pip install pymysql


- if still getting no module found 'mypymysqlsql', we might want to 

- Create the virtual environment in your dev dir: $ python(3) -m venv venv

    - Virtual environments: If you’re using Conda or venv, activate it first before installing the 'pip install pymysql'

- Activate the virtual environment: $ . venv/bin/activate (C:\Users\Jake\Desktop\SQL\sql-projects\sql-connect-with-python\venv\Scripts>)

- Install your dependency(ies): $ pip install pymysql

- on the top right corner, switch to venv(Python 3.13.7), and rerun all, you might
want to pip install pandas again

### please see README.md for Virtual environments purpose

In [ ]:
# Confirm inside Python
import sys
print(sys.executable)

c:\Users\Jake\AppData\Local\Programs\Python\Python313\python.exe

In [9]:

import csv
import pymysql as MySQLdb

mydb = MySQLdb.connect(host='localhost',
                       user='root',
                       passwd='2diiouli',
                       db='trainingdb')
cursor = mydb.cursor()

### Option 3
#### If you do not have the pandas and sqlalchemy libraries, install them using pip

- pip install pandas
- pip install sqlalchemy

- import csv
- import pandas as pd
- from sqlalchemy import create_engine, types

* engine = create_engine('mysql://root:*Enter password here*@localhost/*Enter Databse name -here*') # enter your password and database names here

- df = pd.read_csv("Excel_file_name.csv", sep=',', quotechar='\'', encoding='utf8') 

- df.to_sql('Table_name', con=engine, index=False, if_exists='append')

### We picked option 2

In [1]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [ ]:
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="2diiouli"
)

print(mydb)

In [ ]:
mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE trainingdb")

In [ ]:
mycursor.execute("SHOW DATABASES")

In [ ]:
for x in mycursor:
    print(x)

In [ ]:
df_employee.columns = df_employee.columns.str.lower()
df_employee.columns = df_employee.columns.str.replace(
    ' ', '_', regex=True)
df_employee.columns

In [ ]:
df_customer.columns = df_customer.columns.str.lower()
df_customer.columns = df_customer.columns.str.replace(' ', '_', regex=True)
df_customer.columns

In [ ]:
df_department.columns = df_department.columns.str.lower()
df_department.columns = df_department.columns.str.replace(
    ' ', '_', regex=True)
df_department.columns

In [ ]:
df_inventory.columns = df_inventory.columns.str.lower()
df_inventory.columns = df_inventory.columns.str.replace(
    ' ', '_', regex=True)
df_inventory.columns

In [ ]:
df_order.columns = df_order.columns.str.lower()
df_order.columns = df_order.columns.str.replace(
    ' ', '_', regex=True)
df_order.columns

In [ ]:
df_product.columns = df_product.columns.str.lower()
df_product.columns = df_product.columns.str.replace(
    ' ', '_', regex=True)
df_product.columns

In [ ]:
df_store.columns = df_store.columns.str.lower()
df_store.columns = df_store.columns.str.replace(
    ' ', '_', regex=True)
df_store.columns


#### below code is showing error, but its actually generate the table in the DB

In [ ]:
employees_data = csv.reader('Employees.csv')
for row in employees_data:

    cursor.execute("""
            CREATE TABLE Employees(
                EmployeeId INT PRIMARY KEY,
                FIRST_NAME VARCHAR(50),
                LAST_NAME VARCHAR(50),
                BIRTHDAY DATE,
                EMAIL VARCHAR(50),
                PHONE_NUMBER VARCHAR(50),
                HIRE_DATE DATE,
                JOB_TITLE VARCHAR(50),
                AGE VARCHAR(10),
                SALARY VARCHAR(50),
                COMMISSION VARCHAR(50),
                ManagerId VARCHAR(50),
                DepartmentId VARCHAR(50),
                Name VARCHAR(50))""")

In [ ]:
customers_data = csv.reader('Customers.csv')
for row in customers_data:

    cursor.execute("""
            CREATE TABLE Customers(
                customer_number INT PRIMARY KEY,
                first_name VARCHAR(50),
                last_name VARCHAR(50),
                address VARCHAR(200),
                city VARCHAR(50),
                province VARCHAR(50),
                country VARCHAR(10),
                postal_code VARCHAR(50),
                phone VARCHAR(50),
                email VARCHAR(50))""")

In [ ]:
departments_data = csv.reader('Departments.csv')
for row in departments_data:

    cursor.execute("""
            CREATE TABLE Departments(
                departmentid INT PRIMARY KEY,
                department VARCHAR(50))""")

In [ ]:
inventory_data = csv.reader('Inventory.csv')
for row in inventory_data:

    cursor.execute("""
            CREATE TABLE Inventory(
                warehouse_number VARCHAR(50),
                product_number VARCHAR(50),
                on_hand_units VARCHAR(50),
                in_transit_units VARCHAR(50),
                on_order_units VARCHAR(50),
                transfer_on_order_units VARCHAR(50),
                allocated_units VARCHAR(50),
                held_units VARCHAR(50),
                reserve_on_hand VARCHAR(50),
                reserve_on_order VARCHAR(50),
                available_units VARCHAR(50),
                average_cost VARCHAR(50),
                on_hand_cost VARCHAR(50),
                in_transit_cost VARCHAR(50),
                transfer_on_order_cost VARCHAR(50),
                allocated_cost VARCHAR(50),
                held_cost VARCHAR(50),
                reserve_on_hand_cost VARCHAR(50),
                reserve_on_order_cost VARCHAR(50),
                on_order_cost VARCHAR(50)
                   )""")

In [ ]:
orders_data = csv.reader('Orders.csv')
for row in orders_data:

    cursor.execute("""
            CREATE TABLE Orders(
                customer_number VARCHAR(50),
                store_number VARCHAR(50),
                order_number VARCHAR(50),
                order_date VARCHAR(50),
                target_ship_date VARCHAR(50),
                product_number VARCHAR(50),
                requested_quantity VARCHAR(50),
                ordered_quantity VARCHAR(50),
                unit_cost VARCHAR(50),
                unit_retail VARCHAR(50),
                part_number VARCHAR(50),
                shipped_quantity VARCHAR(50)
                   )""")

In [ ]:
products_data = csv.reader('Products.csv')
for row in products_data:

    cursor.execute("""
            CREATE TABLE Products(
                product_number VARCHAR(50),
                part_number VARCHAR(50),
                sku_-_description VARCHAR(50),
                price VARCHAR(50),
                category VARCHAR(50),
                category_number VARCHAR(50)
                   )""")

In [ ]:
stores_data = csv.reader('Stores.csv')
for row in departments_data:

    cursor.execute("""
            CREATE TABLE Stores(
                store_number VARCHAR(50),
                salesperson VARCHAR(50),
                managerid VARCHAR(50),
                store_name VARCHAR(50),
                store_city VARCHAR(50),
                store_province VARCHAR(50),
                region_number VARCHAR(50),
                warehouse_number VARCHAR(50),
                district_number VARCHAR(50),
                language VARCHAR(50),
                location VARCHAR(50)
                   )""")

In [ ]:

'''
cursor.execute("""
    DROP TABLE customer
""")
'''

In [ ]:
'''
cursor.execute("""
    DROP TABLE customer
""")
'''

In [ ]:
with open('Employees.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO employees (EmployeeId, FIRST_NAME, LAST_NAME,BIRTHDAY, EMAIL, PHONE_NUMBER,HIRE_DATE,JOB_TITLE,AGE, SALARY, COMMISSION,ManagerId,DepartmentId, Name) VALUES(%s, %s, %s,%s, %s, %s,%s, %s, %s,%s, %s, %s,%s, %s)", row)

In [ ]:
with open('Customers.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO Customers (customer_number, first_name, last_name,address, city, province,country,postal_code,phone, email) VALUES(%s, %s, %s,%s, %s, %s,%s, %s, %s,%s)", row)

In [ ]:
with open('Customers.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO Customers (departmentid, department) VALUES(%s, %s)", row)

In [ ]:
with open('Inventory.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO Inventory (warehouse_number, product_number, on_hand_units,\
       in_transit_units, on_order_units, transfer_on_order_units,\
       allocated_units, held_units, reserve_on_hand, reserve_on_order,\
       available_units, average_cost, on_hand_cost, in_transit_cost,\
       transfer_on_order_cost, allocated_cost, held_cost,\
       reserve_on_hand_cost, reserve_on_order_cost, on_order_cost) VALUES(%s, %s, %s,%s, %s, %s,%s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", row)

In [ ]:
with open('Orders.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO Orders (customer_number, store_number, order_number, order_date, \
       target_ship_date, product_number, requested_quantity,\
       ordered_quantity, unit_cost, unit_retail, part_number,\
       shipped_quantity) VALUES(%s, %s, %s,%s, %s, %s,%s, %s, %s,%s, %s, %s)", row)

In [ ]:
with open('Products.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO Products (product_number, part_number, sku_-_description, price,\
       category, category_number) VALUES(%s, %s, %s,%s, %s, %s)", row)

In [ ]:
with open('Stores.csv', 'r') as f:
    data_reader = csv.reader(f)
    next(data_reader)

    for row in data_reader:
        cursor.execute("INSERT INTO Stores (store_number, salesperson, managerid, store_name, store_city,\
       store_province, region_number, warehouse_number,\
       district_number, language, location) VALUES(%s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s)", row)

In [ ]:
mydb.commit()

In [ ]:

# close cursor and communication with the database
cursor.close()
mydb.close()